name: Docker Image CI

on:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
          id: meta
          uses: docker/metadata-action@v5.5.1
          with:
            images: xinghanking/deepface

      - name: Build and push Docker image
          id: push
          uses: docker/build-push-action@v6.4.0
          with:
            context: .
            file: ./Dockerfile
            push: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}
    
     
